### ISSUE TITLE
GUI Ideas

### ISSUE THREAD

**Issue by Darrah** [beloitcollegecomputerscience/BlockadeGames#1]
Document with ideas for GUI posted to the project.

**Comment by Darrah** [comment]
Create a toy GUI that can be the start of the program.

**Comment by Fraust-Coldmann** [comment]
[Basic Gonu UI Idea Board.pdf](https://github.com/beloitcollegecomputerscience/BlockadeGames/files/8477460/Basic.Gonu.UI.Idea.Board.pdf)

**Comment by Darrah** [comment]
Ready for a pull request.
A couple of suggestions from Darrah,

**Comment by Darrah** [comment]
Finished revision. Making the pull request.

**Comment by Darrah** [comment]
Pull request completed and merged.
