### ISSUE TITLE
Toy GUI

### ISSUE THREAD

**Issue by Darrah** [beloitcollegecomputerscience/BlockadeGames#2]
Create a first version of a GUI front-end to the program

**Comment by Darrah** [comment]
Have initial screens.
Need to upload.
Need to have public methods to set player colors; update "player turn" text box; set the coordinates of the 5 vertices.

**Comment by DavidWang0706** [comment]
[gonu.zip](https://github.com/beloitcollegecomputerscience/BlockadeGames/files/8484297/gonu.zip)

**Comment by KYOH95** [comment]
4/20/22 
Connected Main Game Scene to the javaFX
added Color Scene
added InGame Scene
Connected 3 Scenes together which it can be switching by "action button"

**Comment by Darrah** [comment]
Some code needs to be moved into a JavaFX project. (and tested)
Then make a pull request.

**Comment by aziz16034** [comment]
4/22/2022
-Designed board on scene buidler
-exported fxml file from scene buidler
-Imported and run it on java exclipse

**Comment by Darrah** [comment]
Verify there are hooks for the animation people to use.
